name: hsh_2023_py36
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - cffi=1.14.6=py36h400218f_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.6.5=cuda9.0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - jpeg=9e=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h2818925_1
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=8.3.1=py36h5aabda8_0
  - pip=21.2.2=py36h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.6.13=h12debd9_1
  - pytorch=1.1.0=cuda90py36h8b0c50b_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.3.0=cuda90py36h6edc907_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==0.15.0
    - aiosignal==1.2.0
    - akro==0.0.6
    - astor==0.8.1
    - astunparse==1.6.3
    - atari-py==0.1.15
    - attrs==22.2.0
    - box2d-py==2.3.8
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.12
    - clang==5.0
    - click==8.0.4
    - cloudpickle==2.2.1
    - cma==2.7.0
    - cycler==0.11.0
    - cython==0.29.36
    - dataclasses==0.7
    - decorator==4.4.2
    - distlib==0.3.7
    - dm-tree==0.1.8
    - dowel==0.0.2
    - fasteners==0.19
    - filelock==3.4.1
    - flatbuffers==1.12
    - frozenlist==1.2.0
    - future==0.18.3
    - garage==2019.10.1
    - gast==0.2.2
    - glfw==2.6.2
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.48.2
    - gym==0.12.4
    - h5py==2.10.0
    - idna==3.4
    - imageio==2.15.0
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - joblib==0.12.5
    - jsonschema==3.2.0
    - keras==2.6.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.7
    - matplotlib==3.3.4
    - msgpack==1.0.5
    - mujoco-py==2.1.2.14
    - networkx==2.5.1
    - oauthlib==3.2.2
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - packaging==21.3
    - platformdirs==2.4.0
    - protobuf==4.21.0
    - psutil==5.9.5
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyglet==1.3.3
    - pyparsing==3.1.1
    - pyprind==2.11.3
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pywavelets==1.1.1
    - pyyaml==6.0.1
    - ray==2.4.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.17.2
    - scipy==1.5.4
    - setproctitle==1.2.3
    - tabulate==0.8.10
    - tensorboard==1.15.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - tensorflow==1.15.5
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.5
    - tensorflow-probability==0.9.0
    - termcolor==1.1.0
    - tifffile==2020.9.3
    - torch==1.3.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.17
    - virtualenv==20.17.1
    - werkzeug==2.0.3
    - wrapt==1.12.1
    - zipp==3.6.0
prefix: /home/sih19006/.conda/envs/hsh_2023_py36

